name = "battle_of_gods"
main = "src/worker.ts"
compatibility_date = "2023-05-18"
node_compat = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "battle_of_gods"
database_id = "7b9e1376-97b5-4aa5-bab3-1fa2cd7cc689"

[vars]
SECRET_KEY='f3jK7e0gH%lDnBcN6vXzQ-R1aS4wP5sT8uWx?iC9mEoVbYrGtLpAqOjM6uWxZiC9/EoVbYrGtLpAsT8uWxZ.C9mEoVbYrGtLpAqOjM6uWxZiC9mEoVbYrGtLpAqOjM6'